# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o ossec-metrics cmd/ossec-metrics/main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: artifact # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ossec-metrics
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: false

    #- name: Test
    #  run: go test -v -o ossec-metrics cmd/ossec-metrics/main.go
