# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for ARMv7
      run: GOOS=linux GOARCH=arm GOARM=7 go build -v -o ossec-metrics-armv7 cmd/ossec-metrics/main.go

    - name: Build for ARM64
      run: GOOS=linux GOARCH=arm64 go build -v -o ossec-metrics-arm64 cmd/ossec-metrics/main.go

    - name: Build for AMD64
      run: GOOS=linux GOARCH=amd64 go build -v -o ossec-metrics-amd64 cmd/ossec-metrics/main.go

    - name: Build for i386
      run: GOOS=linux GOARCH=386 go build -v -o ossec-metrics-i386 cmd/ossec-metrics/main.go

    - name: Upload ARMv7
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: armv7 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ossec-metrics-armv7
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: false

    - name: Upload ARM64
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: arm64 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ossec-metrics-arm64
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: false

    - name: Upload AMD64
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: amd64 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ossec-metrics-amd64
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: false

    - name: Upload i386
      uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: i386 # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ossec-metrics-i386
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: false

    #- name: Test
    #  run: go test -v -o ossec-metrics cmd/ossec-metrics/main.go
